# Cloudflare Pages configuration
[build]
command = "npm run build:simple && npm run fix-static-export"
publish = "out"

[build.environment]
NODE_VERSION = "20"
NPM_FLAGS = "--prefer-offline --no-audit"
NODE_OPTIONS = "--max-old-space-size=4096"
NEXT_TELEMETRY_DISABLED = "1"
NEXT_BUILD_LINT = "false"

# Environment variables
[env.production]
NODE_ENV = "production"
NEXT_PUBLIC_SITE_URL = "https://litong.pages.dev"

[env.preview]
NODE_ENV = "production"
NEXT_PUBLIC_SITE_URL = "https://litong.pages.dev"