# Cloudflare Pages configuration
[build]
command = "npm run build:cloudflare"
publish = "out"

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--production=false"

# Environment variables
[env.production]
NODE_ENV = "production"
NEXT_PUBLIC_SITE_URL = "https://litong.pages.dev"

[env.preview]
NODE_ENV = "production"
NEXT_PUBLIC_SITE_URL = "https://litong.pages.dev"