# Cloudflare Pages Configuration
name = "litong-electronics"
compatibility_date = "2024-01-01"

# Pages 构建输出目录
pages_build_output_dir = "out"

# 环境变量
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_SITE_URL = "https://litong.pages.dev"

# 兼容性设置
compatibility_flags = ["nodejs_compat"]