# Cloudflare Pages configuration for Next.js SSR
name = "litong-electronics-website"

# Node.js compatibility for SSR
compatibility_flags = ["nodejs_compat"]

# Environment variables
[env.production.vars]
NODE_ENV = "production"