# Cloudflare Pages Configuration
name = "litong-electronics"
compatibility_date = "2024-01-01"

# Pages 构建输出目录
pages_build_output_dir = "out"

# Node.js 版本配置
[build]
command = "npm run build"
[build.environment]
NODE_VERSION = "20.10.0"

# 环境变量
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_SITE_URL = "https://litong.pages.dev"
NODE_VERSION = "20.10.0"

# 兼容性设置
compatibility_flags = ["nodejs_compat"]