# Cloudflare Pages Configuration - 修复Pages兼容性
name = "litong-electronics"
compatibility_date = "2024-01-01"

# Pages 构建输出目录
pages_build_output_dir = "out"

# 环境变量 - 只保留Pages支持的变量
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_SITE_URL = "https://litong.pages.dev"
NEXT_PHASE = "phase-production-build"
EMERGENCY_BUILD = "true"
NEXT_TELEMETRY_DISABLED = "1"

# 兼容性设置
compatibility_flags = ["nodejs_compat"]