# Cloudflare Pages configuration
# This file is used to configure Cloudflare Pages deployment
# Updated: 2025-09-11

# Project name (required for Pages)
name = "litong-electronics-website"

# Build output directory
pages_build_output_dir = "out"

# Compatibility settings
compatibility_date = "2024-09-11"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[env.production.vars]
NODE_ENV = "production"