name = "litong-electronics-website"
compatibility_date = "2024-09-11"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
[env.production]
compatibility_date = "2024-09-11"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Environment variables
[env.production.vars]
NODE_ENV = "production"

# Site configuration
[[env.production.routes]]
pattern = "*"
custom_domain = true

# Cache configuration
[env.production.cache]
max_age = 86400  # 24 hours