# Cloudflare Pages configuration
# This file is used to configure Cloudflare Pages deployment

# Project name (required for Pages)
name = "litong-electronics-website"

# Build output directory
pages_build_output_dir = ".next"

# Compatibility settings
compatibility_date = "2024-09-11"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[env.production.vars]
NODE_ENV = "production"