name = "litong-electronics"
compatibility_date = "2024-08-29"
pages_build_output_dir = "out"

[build]
command = "npm run build:production"
cwd = "."

[build.environment]
NODE_VERSION = "18"

[env.production.vars]
NEXT_PUBLIC_SANITY_PROJECT_ID = "oquvb2bs"
NEXT_PUBLIC_SANITY_DATASET = "production"
NEXT_PUBLIC_SITE_URL = "https://www.elec-distributor.com"

[[env.production.routes]]
pattern = "www.elec-distributor.com"
zone_name = "elec-distributor.com"
custom_domain = true