# Cloudflare Pages configuration for Next.js static export
name = "litong-electronics-website"

# Build output directory for static export
pages_build_output_dir = "out"

# Build configuration
[build]
command = "npm run build"

# Environment variables for build
[build.environment_variables]
NODE_VERSION = "18"
NODE_ENV = "production"